/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.leninsystem;

import db_connection.db_config;
import javax.swing.JOptionPane;

/**
 *
 * @author predator 300
 */
public class create_user extends javax.swing.JFrame {

    /**
     * Creates new form create_user
     */
    public create_user() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_login1 = new panels.body_login();
        header_login1 = new panels.header_login();
        username = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        su_viewpwd = new javax.swing.JCheckBox();
        su_username = new javax.swing.JTextField();
        su_pwd = new javax.swing.JPasswordField();
        su_cpwd = new javax.swing.JPasswordField();
        su_email = new javax.swing.JTextField();
        su_viewcpwd = new javax.swing.JCheckBox();
        su_submit = new panels.MyButton();
        su_viewepwd = new javax.swing.JCheckBox();
        su_emailpwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        body_login1.setBackground(new java.awt.Color(255, 255, 255));

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setText("Username:");

        username1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username1.setText("Password:");

        username2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username2.setText("Confirm Password:");

        username3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username3.setText("Email:");

        username4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username4.setText("Email Password:");

        su_viewpwd.setText("View");
        su_viewpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_viewpwdActionPerformed(evt);
            }
        });

        su_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        su_pwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        su_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_pwdActionPerformed(evt);
            }
        });

        su_cpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        su_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        su_viewcpwd.setText("View");
        su_viewcpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_viewcpwdActionPerformed(evt);
            }
        });

        su_submit.setText("SUBMIT");
        su_submit.setBorderColor(new java.awt.Color(0, 0, 255));
        su_submit.setColorClick(new java.awt.Color(66, 66, 184));
        su_submit.setColorOver(new java.awt.Color(159, 159, 250));
        su_submit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        su_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_submitActionPerformed(evt);
            }
        });

        su_viewepwd.setText("View");
        su_viewepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_viewepwdActionPerformed(evt);
            }
        });

        su_emailpwd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout body_login1Layout = new javax.swing.GroupLayout(body_login1);
        body_login1.setLayout(body_login1Layout);
        body_login1Layout.setHorizontalGroup(
            body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_login1Layout.createSequentialGroup()
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_login1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(header_login1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                    .addGroup(body_login1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(su_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(body_login1Layout.createSequentialGroup()
                                    .addComponent(username1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(su_pwd))
                                .addGroup(body_login1Layout.createSequentialGroup()
                                    .addComponent(username2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(su_cpwd))
                                .addGroup(body_login1Layout.createSequentialGroup()
                                    .addComponent(username3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(su_email))
                                .addGroup(body_login1Layout.createSequentialGroup()
                                    .addComponent(username4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(su_emailpwd))
                                .addGroup(body_login1Layout.createSequentialGroup()
                                    .addComponent(username)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(su_username, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(su_viewpwd)
                            .addComponent(su_viewcpwd)
                            .addComponent(su_viewepwd))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        body_login1Layout.setVerticalGroup(
            body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_login1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(su_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(username1)
                        .addComponent(su_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(su_viewpwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username2)
                    .addComponent(su_cpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(su_viewcpwd))
                .addGap(30, 30, 30)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username3)
                    .addComponent(su_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username4)
                    .addComponent(su_viewepwd)
                    .addComponent(su_emailpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(su_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void su_viewpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_viewpwdActionPerformed
        // TODO add your handling code here:
        
        if(su_viewpwd.isSelected()) {
            su_pwd.setEchoChar((char)0);
        } else {
            su_pwd.setEchoChar('*');
        }
    }//GEN-LAST:event_su_viewpwdActionPerformed

    private void su_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_su_pwdActionPerformed

    private void su_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_submitActionPerformed
        // TODO add your handling code here:
        String username = su_username.getText().trim();
        String password = new String(su_pwd.getPassword());
        String confirmPassword = new String(su_cpwd.getPassword());
        String email = su_email.getText().trim();
        String emailPassword = su_emailpwd.getText().trim(); // Assuming this is the email password field
        
        // Validate that password and confirm password match
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Password and Confirm Password do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit method if validation fails
        }
        
        // If passwords match, proceed with inserting user into MongoDB
        db_config db = new db_config();
        
        db.insertUser(username, password, email, emailPassword);
    }//GEN-LAST:event_su_submitActionPerformed

    private void su_viewcpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_viewcpwdActionPerformed
        // TODO add your handling code here:
        
        if(su_viewcpwd.isSelected()) {
            su_cpwd.setEchoChar((char)0);
        } else {
            su_cpwd.setEchoChar('*');
        }
    }//GEN-LAST:event_su_viewcpwdActionPerformed

    private void su_viewepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_viewepwdActionPerformed
        // TODO add your handling code here:
        if(su_viewepwd.isSelected()) {
            su_emailpwd.setEchoChar((char)0);
        } else {
            su_emailpwd.setEchoChar('*');
        }
    }//GEN-LAST:event_su_viewepwdActionPerformed

//    /**
//     * @param args the command line arguments
//     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panels.body_login body_login1;
    private panels.header_login header_login1;
    private javax.swing.JPasswordField su_cpwd;
    private javax.swing.JTextField su_email;
    private javax.swing.JPasswordField su_emailpwd;
    private javax.swing.JPasswordField su_pwd;
    private panels.MyButton su_submit;
    private javax.swing.JTextField su_username;
    private javax.swing.JCheckBox su_viewcpwd;
    private javax.swing.JCheckBox su_viewepwd;
    private javax.swing.JCheckBox su_viewpwd;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    // End of variables declaration//GEN-END:variables
}
