/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.leninsystem;
import db_connection.db_config;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author predator 300
 */
public class select_dsb extends javax.swing.JFrame {

    /**
     * Creates new form select
     */
    public select_dsb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_login1 = new panels.body_login();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bidding_btn = new panels.MyButton();
        rfq_btn1 = new panels.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body_login1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bidding_btn.setText("BIDDING");
        bidding_btn.setBorderColor(new java.awt.Color(0, 0, 255));
        bidding_btn.setColorClick(new java.awt.Color(66, 66, 184));
        bidding_btn.setColorOver(new java.awt.Color(159, 159, 250));
        bidding_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bidding_btn.setRadius(10);
        bidding_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidding_btnActionPerformed(evt);
            }
        });

        rfq_btn1.setText("RFQ");
        rfq_btn1.setBorderColor(new java.awt.Color(0, 0, 255));
        rfq_btn1.setColorClick(new java.awt.Color(66, 66, 184));
        rfq_btn1.setColorOver(new java.awt.Color(159, 159, 250));
        rfq_btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rfq_btn1.setRadius(10);
        rfq_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfq_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body_login1Layout = new javax.swing.GroupLayout(body_login1);
        body_login1.setLayout(body_login1Layout);
        body_login1Layout.setHorizontalGroup(
            body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_login1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bidding_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(rfq_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        body_login1Layout.setVerticalGroup(
            body_login1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_login1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(rfq_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bidding_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bidding_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidding_btnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_bidding_btnActionPerformed

    private void rfq_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfq_btn1ActionPerformed
        // TODO add your handling code here:
        RFQ_dsb rfq = new RFQ_dsb();
        rfq.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_rfq_btn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panels.MyButton bidding_btn;
    private panels.body_login body_login1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private panels.MyButton rfq_btn1;
    // End of variables declaration//GEN-END:variables
}
